name: validation_assistant
description: Very simple and light form validation helper. This package contains a limited set of preset methods for validation. Its main task is to more conveniently use its own validation functions.
version: 1.0.3
homepage: https://github.com/EKoretsky/validation_assistant.git

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
